# Generated by Django 3.0.8 on 2020-12-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symposium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('introduction', models.TextField(null=True)),
                ('date', models.DateField(unique=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('personalia', models.TextField()),
                ('symposium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.Symposium')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('symposium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.Symposium')),
            ],
        ),
        migrations.AddConstraint(
            model_name='talk',
            constraint=models.UniqueConstraint(fields=('number', 'symposium'), name='unique_talk_ordering'),
        ),
        migrations.AddConstraint(
            model_name='programitem',
            constraint=models.UniqueConstraint(fields=('number', 'symposium'), name='unique_program_ordering'),
        ),
    ]
