# Generated by Django 3.0.8 on 2020-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposium',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='programitem',
            index=models.Index(fields=['number', 'symposium'], name='annonces_pr_number_074935_idx'),
        ),
        migrations.AddIndex(
            model_name='symposium',
            index=models.Index(fields=['slug'], name='annonces_sy_slug_130bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='symposium',
            index=models.Index(fields=['-date'], name='annonces_sy_date_f17a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['number', 'symposium'], name='annonces_ta_number_6fa49e_idx'),
        ),
    ]
