# Generated by Django 3.2.7 on 2021-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_django_bump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.RemoveField(
            model_name='symposium',
            name='meeting_ID',
        ),
        migrations.RemoveField(
            model_name='symposium',
            name='password',
        ),
        migrations.RemoveField(
            model_name='symposium',
            name='zoom_instructions',
        ),
        migrations.AddField(
            model_name='symposium',
            name='to_be_announced',
            field=models.BooleanField(default=False, help_text='Vink aan als de informatie nog niet volledig is. Het symposium zal in de agenda verschijnen op de homepage, maar krijgt nog niet een aparte pagina.', verbose_name='Nog aan te kondigen'),
        ),
        migrations.AddField(
            model_name='symposium',
            name='zoom_link',
            field=models.CharField(blank=True, help_text='Uit veiligheidsoverwegingen verschijnt de zoomlink pas 3 dagen voor het symposium begint op de website, en hij verdwijnt daarna ook weer automatisch.', max_length=100, null=True, verbose_name='Zoom Link'),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titel'),
        ),
    ]
