# Generated by Django 3.0.8 on 2021-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='symposium',
            name='meeting_ID',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='symposium',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='symposium',
            name='zoom_instructions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
