# Generated by Django 3.0.8 on 2021-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='video_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
