# Generated by Django 3.1.5 on 2021-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_talk_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='include_vids',
            field=models.JSONField(default=list),
        ),
    ]
