# Generated by Django 3.2.7 on 2021-11-17 20:14

from django.db import migrations, models
import levensfilosofie.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_alter_talk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Afgelast'),
        ),
        migrations.AddField(
            model_name='symposium',
            name='canceled_message',
            field=levensfilosofie.fields.CleanHTMLField(blank=True, help_text='Zal verschijnen op de pagina van de annonce en op de startpagina, wanneer daar normaliter ook een aankondiging zou verschijnen.', verbose_name='Bericht bij het aflassen'),
        ),
    ]
