# Generated by Django 3.2.7 on 2022-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_canceled_symposia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposium',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoom Link'),
        ),
    ]
