# Generated by Django 3.2.7 on 2022-05-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_canceled_symposia'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='cover_image_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Omslagfoto'),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoom Link'),
        ),
    ]
