# Generated by Django 3.1.5 on 2021-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_symposium_include_vids'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programitem',
            name='unique_program_ordering',
        ),
        migrations.RemoveConstraint(
            model_name='talk',
            name='unique_talk_ordering',
        ),
        migrations.RemoveIndex(
            model_name='programitem',
            name='annonces_pr_number_074935_idx',
        ),
        migrations.RemoveIndex(
            model_name='talk',
            name='annonces_ta_number_6fa49e_idx',
        ),
        migrations.RemoveField(
            model_name='programitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='number',
        ),
        migrations.AlterField(
            model_name='programitem',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='meeting_ID',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelOptions(
            name='symposium',
            options={'verbose_name_plural': 'Symposia'},
        ),
    ]
