# Generated by Django 3.2.7 on 2022-09-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_alter_symposium_zoom_link'),
        ('annonces', '0007_cover_image'),
    ]

    operations = [
    ]
