# Generated by Django 3.1.5 on 2021-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_admin_panel_modifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symposium',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Symposia'},
        ),
        migrations.AlterField(
            model_name='symposium',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
