# Generated by Django 3.2.15 on 2023-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0009_add_unsplash_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programitem',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Begintijd'),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='photo_id',
            field=models.CharField(blank=True, help_text='Zie de API documentatie: <a href="https://unsplash.com/documentation">https://unsplash.com/documentation</a>', max_length=200, null=True, verbose_name='Omslagfoto (Unsplash ID)'),
        ),
    ]
