# Generated by Django 3.2.15 on 2023-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0010_optional_program_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ondertitel'),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='photo_id',
            field=models.CharField(blank=True, help_text='Zie de <a href="https://unsplash.com/documentation">API documentatie</a>.', max_length=200, null=True, verbose_name='Omslagfoto (Unsplash ID)'),
        ),
    ]
