# Generated by Django 3.2.15 on 2024-10-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0011_add_symposium_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='entrance',
            field=models.CharField(choices=[('voluntary', 'Vrijwillige bijdrage'), ('free', 'Vrij')], default='free', max_length=10, verbose_name='Toegang'),
        ),
    ]
