# Generated by Django 3.2.25 on 2025-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0013_alter_symposium_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposium',
            name='extra_announcement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra mededeling'),
        ),
    ]
