# Generated by Django 3.1.5 on 2021-09-27 13:15

import cloudinary.models
from django.db import migrations, models
import levensfilosofie.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, help_text="Bijv.: 'Prof. dr.'", max_length=20, null=True, verbose_name='Prefix')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Voornaam')),
                ('preposition', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tussenvoegsel')),
                ('last_name', models.CharField(max_length=20, verbose_name='Achternaam')),
                ('suffix', models.CharField(blank=True, help_text="Bijv.: 'MA'", max_length=20, null=True, verbose_name='Suffix')),
                ('personalia', levensfilosofie.fields.CleanHTMLField(verbose_name='Personalia')),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Afbeelding')),
            ],
            options={
                'verbose_name': 'Lid',
                'verbose_name_plural': 'Leden',
            },
        ),
    ]
