# Generated by Django 3.0.8 on 2021-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('preposition', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('suffix', models.CharField(max_length=20, null=True)),
                ('personalia', models.TextField(null=True)),
            ],
        ),
    ]
