# Generated by Django 3.1.5 on 2021-09-27 12:52

import cloudinary.models
from django.db import migrations, models
import levensfilosofie.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Lid', 'verbose_name_plural': 'Leden'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='key',
        ),
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=20, verbose_name='Achternaam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='personalia',
            field=levensfilosofie.fields.CleanHTMLField(default='', verbose_name='Personalia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='prefix',
            field=models.CharField(blank=True, help_text="Bijv.: 'Prof. dr.'", max_length=20, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='member',
            name='preposition',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tussenvoegsel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='suffix',
            field=models.CharField(blank=True, help_text="Bijv.: 'MA'", max_length=20, null=True, verbose_name='Suffix'),
        ),
    ]
