# Generated by Django 3.2.7 on 2022-06-10 08:44

from django.db import migrations, models
import levensfilosofie.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0002_django_bump'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Lid', 'verbose_name_plural': 'Leden'},
        ),
        migrations.AddField(
            model_name='member',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Verberg dit lid in de ledenpagina (lid zal alleen bij naam op de startpagina worden genoemd)', verbose_name='Verborgen'),
        ),
        migrations.AlterField(
            model_name='member',
            name='personalia',
            field=levensfilosofie.fields.CleanHTMLField(blank=True, null=True, verbose_name='Personalia'),
        ),
    ]
